import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const testDir = path.dirname(fileURLToPath(import.meta.url))
const routePath = path.join(testDir, '../server/routes/supportChannels.js')
const indexPath = path.join(testDir, '../server/index.js')
const routeModuleUrl = new URL('../server/routes/supportChannels.js', import.meta.url)

function routeSource() {
  assert.ok(fs.existsSync(routePath), 'support channel route module must exist')
  return fs.readFileSync(routePath, 'utf8')
}

test('support channel management routes require authenticated administrators in order', () => {
  const source = routeSource()
  for (const declaration of [
    "router.get('/', authMiddleware, requireAdmin,",
    "router.post('/', authMiddleware, requireAdmin,",
    "router.put('/:id', authMiddleware, requireAdmin,",
    "router.post('/:id/rotate', authMiddleware, requireAdmin,",
    "router.get('/:id/qrcode.svg', authMiddleware, requireAdmin,"
  ]) {
    assert.ok(source.includes(declaration), `missing protected route declaration: ${declaration}`)
  }
})

test('resolve is authenticated without granting administrator-only access', () => {
  const source = routeSource()
  const declaration = source.match(/router\.get\('\/resolve\/:channelCode',[^\n]+/)
  assert.ok(declaration, 'resolve route must be declared')
  assert.match(declaration[0], /authMiddleware/)
  assert.doesNotMatch(declaration[0], /requireAdmin/)
})

test('application mounts support channel APIs before the SPA fallback', () => {
  const source = fs.readFileSync(indexPath, 'utf8')
  const mount = source.indexOf("app.use('/api/support-channels', supportChannelRoutes)")
  const fallback = source.indexOf('// SPA 回退')
  assert.ok(mount >= 0, 'support channel APIs must be mounted')
  assert.ok(mount < fallback, 'support channel APIs must be mounted before the SPA fallback')
})

test('QR endpoint sends SVG attachment generated by qrcode with an ASCII-safe download header', async () => {
  const source = routeSource()
  assert.match(source, /res\.setHeader\('Content-Type', 'image\/svg\+xml; charset=utf-8'\)/)
  assert.match(source, /res\.setHeader\('Content-Disposition', supportQrContentDisposition\(\)\)/)
  assert.match(source, /QRCode\.toString\(url, \{ type: 'svg', errorCorrectionLevel: 'M', margin: 2, width: 360 \}\)/)
  assert.match(source, /service\.buildSupportUrl\(channel\.channel_code\)/)
  process.env.PUBLIC_APP_URL ||= 'https://help.example.com'
  const { supportQrContentDisposition } = await import(routeModuleUrl)
  assert.equal(typeof supportQrContentDisposition, 'function')
  const header = supportQrContentDisposition('讯飞 T9')
  assert.equal(header, 'attachment; filename="support-qrcode.svg"')
  assert.match(header, /^[\x20-\x7E]+$/)
})

test('admin list adds the server-built canonical support URL to every channel', () => {
  const source = routeSource()
  assert.match(source, /const channels = await service\.list\(req\.user\.id\)/)
  assert.match(source, /data: channels\.map\(channel => \(\{[\s\S]*?supportUrl: service\.buildSupportUrl\(channel\.channel_code\)/)
})

function createResponseRecorder() {
  return {
    statusCode: 200,
    body: null,
    status(code) { this.statusCode = code; return this },
    json(value) { this.body = value; return this }
  }
}

function restoreEnv(name, value) {
  if (value === undefined) delete process.env[name]
  else process.env[name] = value
}

test('support channel router starts locally without PUBLIC_APP_URL and uses the configured URL when supplied', async () => {
  const previousPublicAppUrl = process.env.PUBLIC_APP_URL
  const previousNodeEnv = process.env.NODE_ENV
  const previousPort = process.env.PORT
  try {
    process.env.PUBLIC_APP_URL = ''
    process.env.NODE_ENV = 'development'
    process.env.PORT = '4567'
    const localModule = await import(`${routeModuleUrl.href}?local-startup`)
    assert.ok(localModule.default)
    assert.equal(typeof localModule.supportChannelPublicAppUrl, 'function')
    assert.equal(localModule.supportChannelPublicAppUrl(), 'http://localhost:4567')

    process.env.PUBLIC_APP_URL = 'https://help.example.com/customer'
    assert.equal(localModule.supportChannelPublicAppUrl(), 'https://help.example.com/customer')
    assert.match(routeSource(), /publicAppUrl: supportChannelPublicAppUrl\(\)/)
  } finally {
    restoreEnv('PUBLIC_APP_URL', previousPublicAppUrl)
    restoreEnv('NODE_ENV', previousNodeEnv)
    restoreEnv('PORT', previousPort)
  }
})

test('support channel router keeps production PUBLIC_APP_URL validation strict', async () => {
  const previousPublicAppUrl = process.env.PUBLIC_APP_URL
  const previousNodeEnv = process.env.NODE_ENV
  try {
    process.env.PUBLIC_APP_URL = ''
    process.env.NODE_ENV = 'production'
    await assert.rejects(() => import(`${routeModuleUrl.href}?production-config`), /PUBLIC_APP_URL/)
  } finally {
    restoreEnv('PUBLIC_APP_URL', previousPublicAppUrl)
    restoreEnv('NODE_ENV', previousNodeEnv)
  }
})

test('duplicate create and update failures are mapped to a safe Chinese conflict response', async () => {
  process.env.PUBLIC_APP_URL ||= 'https://help.example.com'
  const { sendMutationError } = await import(routeModuleUrl)
  assert.equal(typeof sendMutationError, 'function')
  const response = createResponseRecorder()
  sendMutationError(response, { code: 'ER_DUP_ENTRY', message: 'duplicate SQL details must not escape' })
  assert.equal(response.statusCode, 409)
  assert.deepEqual(response.body, { ok: false, error: '该产品型号已有启用的支持渠道' })
  const mutationMappings = routeSource().match(/^[ \t]+sendMutationError\(res, error\)/gm) || []
  assert.equal(mutationMappings.length, 3)
})

test('support channel logs expose only bounded stable error codes', async () => {
  process.env.PUBLIC_APP_URL ||= 'https://help.example.com'
  const { stableErrorCode } = await import(routeModuleUrl)
  assert.equal(typeof stableErrorCode, 'function')
  assert.equal(stableErrorCode({ code: 'X'.repeat(80), message: 'secret details' }), 'X'.repeat(64))
  assert.equal(stableErrorCode({ message: 'secret details' }), 'UNKNOWN')
  assert.equal(stableErrorCode({ code: 'raw SQL details' }), 'UNKNOWN')
  const source = routeSource()
  assert.doesNotMatch(source, /console\.error\([^)]*,\s*error\)/)
  assert.match(source, /console\.error\('[^']+'\s*,\s*stableErrorCode\(error\)\)/)
})
